@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
title Loop of Registration of a Skill Process
autonumber

'hide footbox
actor "HRM" as ADM
participant ":CreateTaskUI" as UI
participant ":CreateTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "SkillsRepository" as REP
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSAO



activate ADM

        ADM -> UI : asks to register a Skill

        loop
        activate UI


            UI -> CTRL** : create
            activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getSkillsRepository()
            activate PLAT

            PLAT --> CTRL: skillsRepository
            deactivate PLAT
            CTRL --> UI
            deactivate CTRL

            loop if boolean == false
            UI --> ADM : requests skill Id
                        deactivate UI
                        ADM -> UI : inputs skill Id
                        activate UI

            UI -> CTRL : skillExists(skillId)
            activate CTRL

                CTRL -> REP : exists(skillId)
                activate REP

                    REP --> CTRL : returns boolean
                deactivate REP

                CTRL --> UI : returns boolean
            deactivate CTRL
            end

            loop if boolean == false
            UI --> ADM : asks for the skill name
            deactivate UI
            ADM -> UI : inputs skill name
            activate UI

            UI -> CTRL : nameExists(name)
            activate CTRL

            CTRL -> REP : exists(name)
            activate REP

            REP --> CTRL : returns boolean
            deactivate REP

           CTRL --> UI : returns boolean
           deactivate CTRL
           end
           UI --> ADM : asks for confirmation on the registration
           deactivate UI
           ADM --> UI : negates
           activate UI

            UI --> ADM: rollbacks and runs the UI from the start
    deactivate UI

deactivate ADM

end

@enduml