@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

hide circle
hide methods


class Organization {
    name
    vatNumber
    website
    phone
    email
}
class Agenda {
    entry
    team
    vehicles
}
class Collaborator {
    collaborator id
    name
    birthdate
    admission date
    address
    contact info
    taxpayer
}

class Team{
    minMembers
    maxMembers
    teamMembers
    teamSkills
}

class Entry {
    title
    description
    degree of urgency
    dateBegin
    dateEnd
    status
    green space
}

Organization "1" - "1" Agenda: has >
Agenda "1" - "1..*" Team: has >
Agenda "1" - "1..*" Entry: has >
Team "1" -- "1..*" Collaborator: has >


@enduml