@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "GSM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a new green space
    activate System

        System --> Employee : shows list of Green Space types and asks to select one
    deactivate System

    Employee -> System : selects a Green Space type
    activate System

        System --> Employee : requests data (a name, a location, an area, an address)
    deactivate System

    Employee -> System : types data
    activate System

        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
        activate System

        System --> Employee : displays operation success
            deactivate System

@enduml