@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model


class FM {
    fm id
    username
    password

}

class Vehicle {
    plate id
    brand
    model
    type
    tare
    gross weight
    current km
    register date
    acquistion date
}

class Checkup {
    plate id
    date

}



FM "1" - "1..*" Vehicle : registers and manages >
Vehicle "1" - "1..*" Checkup : has >




@enduml