@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US027 - List all green spaces managed by the GSM
header US027
autonumber

actor GSM as GSM
participant System as System

activate GSM

GSM -> System: Request list of managed green spaces
activate System
    System --> GSM: Green spaces displayed
deactivate System

@enduml