@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as ADM
participant ":ToDoListUI" as UI
participant ":ToDoListController" as CTRL
participant ":Repositories" as RepositorySingleton
participant ":repositories\n:Repositories" as PLAT

participant ":ToDoRepository" as DOUR
participant ":ToDoListRepository" as TDR
participant "entry\n:Entry" as TASK

activate ADM

    ADM -> UI : request to add a new entry to the To-Do List
    activate UI

        UI -> CTRL : getGreenSpacesList()
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getGreenSpacesRepository()
            activate PLAT

                PLAT --> CTRL : greenSpacesRepository
            deactivate PLAT

            CTRL -> DOUR : greenSpacesList()
            activate DOUR

                DOUR --> CTRL : greenSpacesList
            deactivate DOUR

            CTRL --> UI : greenSpacesList
        deactivate CTRL

        UI --> ADM : present list of green spaces for selection
    deactivate UI

    ADM -> UI : select a green space for the new entry
    activate UI

        UI --> ADM : request for details of the new entry (a title, a state, a green space,\n a description, a degree of urgency, a duration)
    deactivate UI

    ADM -> UI : provide details of the new entry
    activate UI

        UI --> ADM : shows all data and requests confirmation
    deactivate UI

    ADM -> UI : confirms data
    activate UI

        UI -> CTRL : addEntry(title, state, greenSpace,\n description, degreeOfUrgency, duration)
        activate CTRL

            CTRL -> PLAT : getToDoListRepository()
            activate PLAT

                PLAT --> CTRL : toDoListRepository
            deactivate PLAT

            CTRL -> TDR : addEntry(title, state, greenSpace,\n description, degreeOfUrgency, duration)
            activate TDR

                TDR -> TASK** : createEntry(title, state, greenSpace,\n description, degreeOfUrgency, duration)
                TDR --> TDR : validateEntry(entry)
                TDR --> TDR : saveEntry(entry)
                TDR --> CTRL : boolean
            deactivate TDR

            CTRL --> UI : boolean
        deactivate CTRL

        UI --> ADM : displays operation success
    deactivate UI

deactivate ADM

@enduml