@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0



class Repositories {
    + getInstance()
    + getGreenSpaceRepository()
    + getToDoListRepository()

}

class GreenSpaceRepository {
    + + getGreenSpaces()

}

class GreenSpaceController {
    + getGreenSpaces()
    + getDegreesOfUrgency()

}

class AddEntryToToDoListUI {
}

class ToDoListController {
    + createEntry(title, description, degreeOfUrgency, duration, status, greenSpace)
}

class DegreeOfUrgency {
    + getDegreesOfUrgency()
}

class ToDoEntryDTO {
    + create(title, description, degreeOfUrgency, duration, status, greenSpace)
}

class ToDoEntryMapper {
    + toDomain(toDoEntryDto)
}

class ToDoEntry {
    + create(title, description, degreeOfUrgency, duration, status, greenSpace)
    + addEntry()
    + validateEntry()
}


AddEntryToToDoListUI .right.> GreenSpaceController
GreenSpaceController ..> GreenSpaceRepository
GreenSpaceController ..> GreenSpace
GreenSpaceController ..> DegreeOfUrgency
GreenSpaceController ..> Repositories
AddEntryToToDoListUI .left> ToDoListController
ToDoListController ..> ToDoEntryDTO
ToDoListController ..> Repositories
ToDoListController ..> ToDoEntryMapper
ToDoEntryMapper ..> ToDoEntry




@enduml