@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "HRM" as HRM
participant ":CreateCollaboratorUI" as UI
participant ":CreateCollaboratorController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "jobRepository:\nJobRepository" as JobRepository
participant "organization\n:Organization" as ORG
participant "collaborator\n:Collaborator" as Collaborator


activate HRM

        HRM -> UI : asks to register a collaborator

        activate UI

'            UI --> HRM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getJobs()
            activate CTRL
                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getJobRepository()
                activate PLAT

                    PLAT --> CTRL: jobRepository
                deactivate PLAT

                CTRL -> JobRepository : getJobs()
                activate JobRepository

                    JobRepository --> CTRL : jobList
                deactivate JobRepository


                CTRL --> UI : jobsList

            deactivate CTRL


            UI --> HRM : requests data (a name, a birthdate, an admission data,\n an address, a contact info (mobile and email), taxpayer number,\n ID doc type, and respective number)
        deactivate UI

    HRM -> UI : types request data
    activate UI
        UI --> UI : keepData(name, birthdate, admissionData,\n address, email, mobileNumber, taxpayerNumber,\n idDocType, respectiveNumber)

        deactivate CTRL
        UI --> HRM : shows job list and asks to select one
    deactivate UI

    HRM -> UI : selects a job category
    activate UI
        UI --> UI : keepJob(jobId)
        UI --> HRM : shows all data and requests confirmation
    deactivate UI

    HRM -> UI : confirms data
    activate UI

        UI -> CTRL : createCollaborator(name, birthdate, admissionData,\n address, email, mobileNumber, taxpayerNumber,\n idDocType, respectiveNumber)
        activate CTRL


                CTRL -> CTRL : getJobById(jobId)


                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getJobRepository()
                activate PLAT

                    PLAT -> CTRL : jobRepository
                deactivate PLAT

                CTRL -> JobRepository : getJobById(jobId)
                activate JobRepository

                    JobRepository --> CTRL : job
                deactivate JobRepository
                    CTRL --> CTRL : job


            CTRL -> ORG: createCollaborator(name, birthdate, admissionData,\n address, email, mobileNumber, taxpayerNumber,\n idDocType, respectiveNumber, hrm, job)
            activate ORG
deactivate CTRL
                ORG -> Collaborator**: create(name, birthdate, admissionData,\n address, email, mobileNumber, taxpayerNumber,\n idDocType, respectiveNumber, hrm)
                ORG -> ORG: addCollaborator(collaborator)



                    ORG -> ORG: validateCollaborator(collaborator)







                ORG --> CTRL : collaborator

            deactivate ORG

            CTRL --> UI: collaborator
            deactivate CTRL
            UI --> HRM: displays operation success
    deactivate UI

deactivate HRM

@enduml