@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class PostponeAnEntryUI{
}


class PostponeAnEntryController{
-AgendaRepository agendaRepository
    + PostponeAnEntryController(agendaRepository)
    + getPlannedAndPostponedTask()
 }

class Repositories {
    - Repositories(): Repositories
    + getInstance() : Repositories
    + getAgendaRepository() : Repositories
}


class AgendaRepository {
    + getPlannedAndPostponedTask()

}

class  Entry{
        -title
        -description
        -urgencyLevel
        -expectedDuration
        -state
        -greenSpace

}

class EntryDto{
+TaskEntry
+Date
+Time
}


AgendaRepository --> "*" Entry: contains
PostponeAnEntryUI .>  PostponeAnEntryController
PostponeAnEntryController ...r> Repositories : repositories
PostponeAnEntryUI .> EntryDto
PostponeAnEntryController ..> EntryDto
Repositories -> Repositories : instance
Repositories "1" --> "*" Entry
Repositories ---> "1" AgendaRepository

 PostponeAnEntryController ......>  Entry : Entry
 PostponeAnEntryController ...> "1" AgendaRepository : AgendaRepository
@enduml