@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing true
skinparam classAttributeIconSize 0

class PostponeEntryUI {
}

class PostponeEntryController {
    + PostponeEntryController(agendaRepository)
    + getAgendaEntries()
    + postponeEntry(entryID, newDate)
}

class Repositories {
    Repositories()
    + getInstance()
    + getAgendaRepository()
}

class AgendaRepository {
    + getAgendaEntries()
    + postponeEntry(entryID, newDate)
}

class AgendaEntry {
    entryID
    taskDescription
    assignedTeam
    vehicles
    duration
    status
    + postponeEntry(newDate)
    + validateNewDate(newDate)
}

PostponeEntryUI .> PostponeEntryController
PostponeEntryController .> Repositories : repositories
Repositories --> "1" AgendaRepository
AgendaRepository --> "1" AgendaEntry
@enduml
