@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Green Space Manager (GSM)" as GSM
participant ":PostponeUI" as UI
participant ":PostponeController" as CTRL
participant ":AgendaRepository" as REP
participant "repositories\n:Repositories" as PLAT
participant "agendaRepository:\nAgendaRepository" as AGREP
participant "agendaEntry:\nAgendaEntry" as AgendaEntry

activate GSM

GSM -> UI : Requests to postpone an entry in the Agenda
activate UI
UI -> CTRL** : Create
UI -> CTRL : getAgendaEntries()
activate CTRL
CTRL -> REP : getInstance()
activate REP
REP --> CTRL: repositories
deactivate REP
CTRL -> PLAT : getAgendaRepository()
activate PLAT
PLAT --> CTRL: agendaRepository
deactivate PLAT
CTRL -> AGREP : getAgendaEntries()
activate AGREP
AGREP --> CTRL : agendaEntries
deactivate AGREP
CTRL --> UI : agendaEntries
deactivate CTRL
UI --> GSM : Displays list of agenda entries and requests entry selection
deactivate UI

GSM -> UI : Selects an agenda entry to postpone and requests new date
activate UI
UI --> GSM : Input new date for postponement
deactivate UI

GSM -> UI : Confirms the postponement request
activate UI
UI -> CTRL : postponeEntry(newDate)
activate CTRL
CTRL -> AGREP : postponeEntry(entryID, newDate)
activate AGREP
AGREP -> AgendaEntry : postponeEntry(newDate)
activate AgendaEntry
AgendaEntry -> AgendaEntry : validateNewDate(newDate)
AgendaEntry --> AGREP : updatedAgendaEntry
deactivate AgendaEntry
AGREP --> CTRL : updatedAgendaEntry
deactivate AGREP
CTRL --> UI : Confirmation message
deactivate CTRL
UI --> GSM : Displays confirmation message
deactivate UI

deactivate GSM

@enduml
