@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing true
skinparam classAttributeIconSize 0

class AgendaEntry {
    entryID: int
    taskDescription: string
    assignedTeam: string
    vehicles: string
    duration: string
    status: string
}

class GSM {
    gsmID: int
    username: string
    password: string
}

class GreenSpace {
    spaceID: int
    spaceType: string
    area: string
}

AgendaEntry "1" -- "1..*" GSM : assignedTo >
AgendaEntry "1" -- "1" GreenSpace : relatesTo >
@enduml
