@startuml
title Design for US027 - List all green spaces managed by the GSM
header Design for US027
autonumber

actor GSM as GSM
participant "UI" as UI
participant "GreenSpaceController" as GreenSpaceController
participant "GreenSpaceRepository" as GreenSpaceRepo

activate GSM

GSM -> UI: Request list of managed green spaces
activate UI
UI -> GreenSpaceController: Request list of managed green spaces
activate GreenSpaceController
GreenSpaceController -> GreenSpaceRepo: Retrieve managed green spaces
activate GreenSpaceRepo
GreenSpaceRepo --> GreenSpaceController: List of managed green spaces
deactivate GreenSpaceRepo
GreenSpaceController --> UI: List of managed green spaces
deactivate GreenSpaceController
UI --> GSM: Display filtered green spaces
deactivate UI

deactivate GSM
@enduml