@startuml
title Design for US027 - List all green spaces managed by the GSM
header Design for US027
autonumber

actor GSM as GSM
participant "GreenSpaceUI" as GreenSpaceUI
participant "GreenSpaceController" as GreenSpaceController
participant "GreenSpaceRepository" as GreenSpaceRepo

activate GSM

GSM -> GreenSpaceUI: Request list of \nmanaged green spaces
activate GreenSpaceUI
GreenSpaceUI -> GreenSpaceController: Request list of \nmanaged green spaces
activate GreenSpaceController
GreenSpaceController -> GreenSpaceRepo: Retrieve managed green spaces
activate GreenSpaceRepo
GreenSpaceRepo --> GreenSpaceController: List of managed green spaces
deactivate GreenSpaceRepo
GreenSpaceController --> GreenSpaceUI: List of managed\n green spaces
deactivate GreenSpaceController
GreenSpaceUI --> GSM: Green Spaces displayed
deactivate  GreenSpaceUI

deactivate GSM
@enduml