@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US008 - List the vehicles needing check-up
header US008
autonumber

actor "FM" as fm
participant ":System" as System

activate fm

    fm -> System : Request list of vehicles needing check-up.
    activate System
        fm -> System : Selects order in which to view the list.
        System --> System : Retrieval of vehicle\n information.
        note right System : Lists the vehicles details:\nPlate number\nBrand\nModel\nReason
        System -> fm : Returns the list.
    deactivate System

@enduml