@startuml
actor "Green Space Manager" as gsm
participant "System" as System
title US026 - Assign one or more vehicles to an entry in the Agenda.
header US026
autonumber

activate gsm

gsm -> System : Request to assign vehicle(s) to an agenda entry

activate System

    System --> gsm : Shows available agenda entries\n and asks for the selection of one
deactivate

gsm -> System : Selects one agenda entry
activate System

System --> gsm : List of available vehicles


loop While GSM wants to add vehicles
System --> gsm : Asks for the selection of a vehicle

gsm -> System : Selects vehicle
end loop

System --> gsm : Confirmation of assignment
deactivate System
'Metodo no controller chamado AssignVehicleToAgendaEntry(AgendaEntry, Vehicle)
deactivate gsm
@enduml