@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class CancelAnEntryUI{
}


class CancelAnEntryController{
-AgendaRepository agendaRepository
    + CancelAnEntryController(agendaRepository)
    + getPlannedAndPostponedTask()
 }

class Repositories {
    - Repositories(): Repositories
    + getInstance() : Repositories
    + getAgendaRepository() : Repositories
}


class AgendaRepository {
    + getPlannedAndPostponedTask()

}

class  Entry{
        -title
        -description
        -urgencyLevel
        -expectedDuration
        -state
        -greenSpace

}

class EntryDto{
+TaskEntry
+Date
+Time
}


AgendaRepository --> "*" Entry: contains
CancelAnEntryUI .>  CancelAnEntryController
CancelAnEntryController ...r> Repositories : repositories
CancelAnEntryUI .> EntryDto
CancelAnEntryController ..> EntryDto
Repositories -> Repositories : instance
Repositories "1" --> "*" Entry
Repositories ---> "1" AgendaRepository

 CancelAnEntryController ......>  Entry : Entry
 CancelAnEntryController ...> "1" AgendaRepository : AgendaRepository
@enduml