@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "HRM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a new collaborator
    activate System

        System --> Employee : requests data (a name, a birthdate, an admission data,\n an address, a contact info (mobile and email))
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : shows job list and asks to select one
    deactivate System

    Employee -> System : selects a job category
    activate System

        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml