@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

hide circle
hide methods

class GreenSpaceManager {
    ID
    Name
}

class GreenSpace {
    ID
    Name
    Location
    Area
    Description
}

GreenSpaceManager "1" - "0..*" GreenSpace : "manages"

@enduml