@startuml
class AgendaUI {

}

class AgendaController {

}

class AgendaRepository {

}

class VehicleRepository {

}

class AgendaEntry {

}

AgendaUI --> AgendaController
AgendaController --> AgendaRepository
AgendaController --> VehicleRepository
AgendaRepository --> AgendaEntry
AgendaController --> AgendaEntry

@enduml